name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: Install Go1.16 Beta 1
        run: go get golang.org/dl/go1.16beta1 && go1.16beta1 download
      - name: Run tests
        run: go1.16beta1 test -v -race ./...
      #- name: Run lint
        #uses: golangci/golangci-lint-action@v2
        #with:
          #version: v1.29
      - name: Build examples
        env:
          CGO_ENABLED: 0
        run: |
          go1.16beta1 build -o example ./cmd/example
          go1.16beta1 build -o pixel ./cmd/pixel
